(cl:defpackage stage_ros-srv
  (:use )
  (:export
   "GETMODELPOSE"
   "<GETMODELPOSE-REQUEST>"
   "GETMODELPOSE-REQUEST"
   "<GETMODELPOSE-RESPONSE>"
   "GETMODELPOSE-RESPONSE"
   "SETMODELPOSE"
   "<SETMODELPOSE-REQUEST>"
   "SETMODELPOSE-REQUEST"
   "<SETMODELPOSE-RESPONSE>"
   "SETMODELPOSE-RESPONSE"
  ))

