// Generated by gencpp from file stage_ros/GetModelPose.msg
// DO NOT EDIT!


#ifndef STAGE_ROS_MESSAGE_GETMODELPOSE_H
#define STAGE_ROS_MESSAGE_GETMODELPOSE_H

#include <ros/service_traits.h>


#include <stage_ros/GetModelPoseRequest.h>
#include <stage_ros/GetModelPoseResponse.h>


namespace stage_ros
{

struct GetModelPose
{

typedef GetModelPoseRequest Request;
typedef GetModelPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetModelPose
} // namespace stage_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stage_ros::GetModelPose > {
  static const char* value()
  {
    return "19acca60f2f0ae24d400ff17db3e5408";
  }

  static const char* value(const ::stage_ros::GetModelPose&) { return value(); }
};

template<>
struct DataType< ::stage_ros::GetModelPose > {
  static const char* value()
  {
    return "stage_ros/GetModelPose";
  }

  static const char* value(const ::stage_ros::GetModelPose&) { return value(); }
};


// service_traits::MD5Sum< ::stage_ros::GetModelPoseRequest> should match
// service_traits::MD5Sum< ::stage_ros::GetModelPose >
template<>
struct MD5Sum< ::stage_ros::GetModelPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stage_ros::GetModelPose >::value();
  }
  static const char* value(const ::stage_ros::GetModelPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stage_ros::GetModelPoseRequest> should match
// service_traits::DataType< ::stage_ros::GetModelPose >
template<>
struct DataType< ::stage_ros::GetModelPoseRequest>
{
  static const char* value()
  {
    return DataType< ::stage_ros::GetModelPose >::value();
  }
  static const char* value(const ::stage_ros::GetModelPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stage_ros::GetModelPoseResponse> should match
// service_traits::MD5Sum< ::stage_ros::GetModelPose >
template<>
struct MD5Sum< ::stage_ros::GetModelPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stage_ros::GetModelPose >::value();
  }
  static const char* value(const ::stage_ros::GetModelPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stage_ros::GetModelPoseResponse> should match
// service_traits::DataType< ::stage_ros::GetModelPose >
template<>
struct DataType< ::stage_ros::GetModelPoseResponse>
{
  static const char* value()
  {
    return DataType< ::stage_ros::GetModelPose >::value();
  }
  static const char* value(const ::stage_ros::GetModelPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STAGE_ROS_MESSAGE_GETMODELPOSE_H
