// Generated by gencpp from file stage_ros/GetModelPoseRequest.msg
// DO NOT EDIT!


#ifndef STAGE_ROS_MESSAGE_GETMODELPOSEREQUEST_H
#define STAGE_ROS_MESSAGE_GETMODELPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stage_ros
{
template <class ContainerAllocator>
struct GetModelPoseRequest_
{
  typedef GetModelPoseRequest_<ContainerAllocator> Type;

  GetModelPoseRequest_()
    : model_name()  {
    }
  GetModelPoseRequest_(const ContainerAllocator& _alloc)
    : model_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _model_name_type;
  _model_name_type model_name;





  typedef boost::shared_ptr< ::stage_ros::GetModelPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stage_ros::GetModelPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetModelPoseRequest_

typedef ::stage_ros::GetModelPoseRequest_<std::allocator<void> > GetModelPoseRequest;

typedef boost::shared_ptr< ::stage_ros::GetModelPoseRequest > GetModelPoseRequestPtr;
typedef boost::shared_ptr< ::stage_ros::GetModelPoseRequest const> GetModelPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stage_ros::GetModelPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stage_ros::GetModelPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stage_ros::GetModelPoseRequest_<ContainerAllocator1> & lhs, const ::stage_ros::GetModelPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.model_name == rhs.model_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stage_ros::GetModelPoseRequest_<ContainerAllocator1> & lhs, const ::stage_ros::GetModelPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stage_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stage_ros::GetModelPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stage_ros::GetModelPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stage_ros::GetModelPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stage_ros::GetModelPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stage_ros::GetModelPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stage_ros::GetModelPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stage_ros::GetModelPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea31c8eab6fc401383cf528a7c0984ba";
  }

  static const char* value(const ::stage_ros::GetModelPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea31c8eab6fc4013ULL;
  static const uint64_t static_value2 = 0x83cf528a7c0984baULL;
};

template<class ContainerAllocator>
struct DataType< ::stage_ros::GetModelPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stage_ros/GetModelPoseRequest";
  }

  static const char* value(const ::stage_ros::GetModelPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stage_ros::GetModelPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string model_name\n"
;
  }

  static const char* value(const ::stage_ros::GetModelPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stage_ros::GetModelPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.model_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetModelPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stage_ros::GetModelPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stage_ros::GetModelPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "model_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.model_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STAGE_ROS_MESSAGE_GETMODELPOSEREQUEST_H
