// Generated by gencpp from file stage_ros/GetModelPoseResponse.msg
// DO NOT EDIT!


#ifndef STAGE_ROS_MESSAGE_GETMODELPOSERESPONSE_H
#define STAGE_ROS_MESSAGE_GETMODELPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stage_ros
{
template <class ContainerAllocator>
struct GetModelPoseResponse_
{
  typedef GetModelPoseResponse_<ContainerAllocator> Type;

  GetModelPoseResponse_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , a(0.0)
    , success(false)  {
    }
  GetModelPoseResponse_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , a(0.0)
    , success(false)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _a_type;
  _a_type a;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::stage_ros::GetModelPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stage_ros::GetModelPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetModelPoseResponse_

typedef ::stage_ros::GetModelPoseResponse_<std::allocator<void> > GetModelPoseResponse;

typedef boost::shared_ptr< ::stage_ros::GetModelPoseResponse > GetModelPoseResponsePtr;
typedef boost::shared_ptr< ::stage_ros::GetModelPoseResponse const> GetModelPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stage_ros::GetModelPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stage_ros::GetModelPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stage_ros::GetModelPoseResponse_<ContainerAllocator1> & lhs, const ::stage_ros::GetModelPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.a == rhs.a &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stage_ros::GetModelPoseResponse_<ContainerAllocator1> & lhs, const ::stage_ros::GetModelPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stage_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stage_ros::GetModelPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stage_ros::GetModelPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stage_ros::GetModelPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stage_ros::GetModelPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stage_ros::GetModelPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stage_ros::GetModelPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stage_ros::GetModelPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "636b2c5357b86400c34dcc02d60c0a78";
  }

  static const char* value(const ::stage_ros::GetModelPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x636b2c5357b86400ULL;
  static const uint64_t static_value2 = 0xc34dcc02d60c0a78ULL;
};

template<class ContainerAllocator>
struct DataType< ::stage_ros::GetModelPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stage_ros/GetModelPoseResponse";
  }

  static const char* value(const ::stage_ros::GetModelPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stage_ros::GetModelPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 a\n"
"bool success\n"
;
  }

  static const char* value(const ::stage_ros::GetModelPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stage_ros::GetModelPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.a);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetModelPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stage_ros::GetModelPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stage_ros::GetModelPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "a: ";
    Printer<float>::stream(s, indent + "  ", v.a);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STAGE_ROS_MESSAGE_GETMODELPOSERESPONSE_H
