// Generated by gencpp from file stage_ros/SetModelPose.msg
// DO NOT EDIT!


#ifndef STAGE_ROS_MESSAGE_SETMODELPOSE_H
#define STAGE_ROS_MESSAGE_SETMODELPOSE_H

#include <ros/service_traits.h>


#include <stage_ros/SetModelPoseRequest.h>
#include <stage_ros/SetModelPoseResponse.h>


namespace stage_ros
{

struct SetModelPose
{

typedef SetModelPoseRequest Request;
typedef SetModelPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetModelPose
} // namespace stage_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stage_ros::SetModelPose > {
  static const char* value()
  {
    return "c397a50cbfa6253f64e0ed985ef4b9c0";
  }

  static const char* value(const ::stage_ros::SetModelPose&) { return value(); }
};

template<>
struct DataType< ::stage_ros::SetModelPose > {
  static const char* value()
  {
    return "stage_ros/SetModelPose";
  }

  static const char* value(const ::stage_ros::SetModelPose&) { return value(); }
};


// service_traits::MD5Sum< ::stage_ros::SetModelPoseRequest> should match
// service_traits::MD5Sum< ::stage_ros::SetModelPose >
template<>
struct MD5Sum< ::stage_ros::SetModelPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stage_ros::SetModelPose >::value();
  }
  static const char* value(const ::stage_ros::SetModelPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stage_ros::SetModelPoseRequest> should match
// service_traits::DataType< ::stage_ros::SetModelPose >
template<>
struct DataType< ::stage_ros::SetModelPoseRequest>
{
  static const char* value()
  {
    return DataType< ::stage_ros::SetModelPose >::value();
  }
  static const char* value(const ::stage_ros::SetModelPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stage_ros::SetModelPoseResponse> should match
// service_traits::MD5Sum< ::stage_ros::SetModelPose >
template<>
struct MD5Sum< ::stage_ros::SetModelPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stage_ros::SetModelPose >::value();
  }
  static const char* value(const ::stage_ros::SetModelPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stage_ros::SetModelPoseResponse> should match
// service_traits::DataType< ::stage_ros::SetModelPose >
template<>
struct DataType< ::stage_ros::SetModelPoseResponse>
{
  static const char* value()
  {
    return DataType< ::stage_ros::SetModelPose >::value();
  }
  static const char* value(const ::stage_ros::SetModelPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STAGE_ROS_MESSAGE_SETMODELPOSE_H
