// Generated by gencpp from file stage_ros/SetModelPoseResponse.msg
// DO NOT EDIT!


#ifndef STAGE_ROS_MESSAGE_SETMODELPOSERESPONSE_H
#define STAGE_ROS_MESSAGE_SETMODELPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stage_ros
{
template <class ContainerAllocator>
struct SetModelPoseResponse_
{
  typedef SetModelPoseResponse_<ContainerAllocator> Type;

  SetModelPoseResponse_()
    : success(false)  {
    }
  SetModelPoseResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::stage_ros::SetModelPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stage_ros::SetModelPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetModelPoseResponse_

typedef ::stage_ros::SetModelPoseResponse_<std::allocator<void> > SetModelPoseResponse;

typedef boost::shared_ptr< ::stage_ros::SetModelPoseResponse > SetModelPoseResponsePtr;
typedef boost::shared_ptr< ::stage_ros::SetModelPoseResponse const> SetModelPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stage_ros::SetModelPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stage_ros::SetModelPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stage_ros::SetModelPoseResponse_<ContainerAllocator1> & lhs, const ::stage_ros::SetModelPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stage_ros::SetModelPoseResponse_<ContainerAllocator1> & lhs, const ::stage_ros::SetModelPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stage_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stage_ros::SetModelPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stage_ros::SetModelPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stage_ros::SetModelPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stage_ros::SetModelPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stage_ros::SetModelPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stage_ros::SetModelPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stage_ros::SetModelPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::stage_ros::SetModelPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::stage_ros::SetModelPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stage_ros/SetModelPoseResponse";
  }

  static const char* value(const ::stage_ros::SetModelPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stage_ros::SetModelPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::stage_ros::SetModelPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stage_ros::SetModelPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetModelPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stage_ros::SetModelPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stage_ros::SetModelPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STAGE_ROS_MESSAGE_SETMODELPOSERESPONSE_H
