// Generated by gencpp from file stage_ros/SetModelPoseRequest.msg
// DO NOT EDIT!


#ifndef STAGE_ROS_MESSAGE_SETMODELPOSEREQUEST_H
#define STAGE_ROS_MESSAGE_SETMODELPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stage_ros
{
template <class ContainerAllocator>
struct SetModelPoseRequest_
{
  typedef SetModelPoseRequest_<ContainerAllocator> Type;

  SetModelPoseRequest_()
    : model_name()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , a(0.0)  {
    }
  SetModelPoseRequest_(const ContainerAllocator& _alloc)
    : model_name(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , a(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _model_name_type;
  _model_name_type model_name;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::stage_ros::SetModelPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stage_ros::SetModelPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetModelPoseRequest_

typedef ::stage_ros::SetModelPoseRequest_<std::allocator<void> > SetModelPoseRequest;

typedef boost::shared_ptr< ::stage_ros::SetModelPoseRequest > SetModelPoseRequestPtr;
typedef boost::shared_ptr< ::stage_ros::SetModelPoseRequest const> SetModelPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stage_ros::SetModelPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stage_ros::SetModelPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stage_ros::SetModelPoseRequest_<ContainerAllocator1> & lhs, const ::stage_ros::SetModelPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.model_name == rhs.model_name &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stage_ros::SetModelPoseRequest_<ContainerAllocator1> & lhs, const ::stage_ros::SetModelPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stage_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stage_ros::SetModelPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stage_ros::SetModelPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stage_ros::SetModelPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stage_ros::SetModelPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stage_ros::SetModelPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stage_ros::SetModelPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stage_ros::SetModelPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f8718ff3dd8f22ab872a0321d8f1f61e";
  }

  static const char* value(const ::stage_ros::SetModelPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf8718ff3dd8f22abULL;
  static const uint64_t static_value2 = 0x872a0321d8f1f61eULL;
};

template<class ContainerAllocator>
struct DataType< ::stage_ros::SetModelPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stage_ros/SetModelPoseRequest";
  }

  static const char* value(const ::stage_ros::SetModelPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stage_ros::SetModelPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string model_name\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 a\n"
;
  }

  static const char* value(const ::stage_ros::SetModelPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stage_ros::SetModelPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.model_name);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetModelPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stage_ros::SetModelPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stage_ros::SetModelPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "model_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.model_name);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "a: ";
    Printer<float>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STAGE_ROS_MESSAGE_SETMODELPOSEREQUEST_H
