// Generated by gencpp from file physarum_simulation/LockTaskResponse.msg
// DO NOT EDIT!


#ifndef PHYSARUM_SIMULATION_MESSAGE_LOCKTASKRESPONSE_H
#define PHYSARUM_SIMULATION_MESSAGE_LOCKTASKRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace physarum_simulation
{
template <class ContainerAllocator>
struct LockTaskResponse_
{
  typedef LockTaskResponse_<ContainerAllocator> Type;

  LockTaskResponse_()
    : success(false)  {
    }
  LockTaskResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::physarum_simulation::LockTaskResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::physarum_simulation::LockTaskResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LockTaskResponse_

typedef ::physarum_simulation::LockTaskResponse_<std::allocator<void> > LockTaskResponse;

typedef boost::shared_ptr< ::physarum_simulation::LockTaskResponse > LockTaskResponsePtr;
typedef boost::shared_ptr< ::physarum_simulation::LockTaskResponse const> LockTaskResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::physarum_simulation::LockTaskResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::physarum_simulation::LockTaskResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::physarum_simulation::LockTaskResponse_<ContainerAllocator1> & lhs, const ::physarum_simulation::LockTaskResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::physarum_simulation::LockTaskResponse_<ContainerAllocator1> & lhs, const ::physarum_simulation::LockTaskResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace physarum_simulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::physarum_simulation::LockTaskResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::physarum_simulation::LockTaskResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::physarum_simulation::LockTaskResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::physarum_simulation::LockTaskResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::physarum_simulation::LockTaskResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::physarum_simulation::LockTaskResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::physarum_simulation::LockTaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::physarum_simulation::LockTaskResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::physarum_simulation::LockTaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "physarum_simulation/LockTaskResponse";
  }

  static const char* value(const ::physarum_simulation::LockTaskResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::physarum_simulation::LockTaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::physarum_simulation::LockTaskResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::physarum_simulation::LockTaskResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LockTaskResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::physarum_simulation::LockTaskResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::physarum_simulation::LockTaskResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHYSARUM_SIMULATION_MESSAGE_LOCKTASKRESPONSE_H
