// Generated by gencpp from file physarum_simulation/LockTask.msg
// DO NOT EDIT!


#ifndef PHYSARUM_SIMULATION_MESSAGE_LOCKTASK_H
#define PHYSARUM_SIMULATION_MESSAGE_LOCKTASK_H

#include <ros/service_traits.h>


#include <physarum_simulation/LockTaskRequest.h>
#include <physarum_simulation/LockTaskResponse.h>


namespace physarum_simulation
{

struct LockTask
{

typedef LockTaskRequest Request;
typedef LockTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LockTask
} // namespace physarum_simulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::physarum_simulation::LockTask > {
  static const char* value()
  {
    return "533c5e19719d65457567739c7f3d4d58";
  }

  static const char* value(const ::physarum_simulation::LockTask&) { return value(); }
};

template<>
struct DataType< ::physarum_simulation::LockTask > {
  static const char* value()
  {
    return "physarum_simulation/LockTask";
  }

  static const char* value(const ::physarum_simulation::LockTask&) { return value(); }
};


// service_traits::MD5Sum< ::physarum_simulation::LockTaskRequest> should match
// service_traits::MD5Sum< ::physarum_simulation::LockTask >
template<>
struct MD5Sum< ::physarum_simulation::LockTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::physarum_simulation::LockTask >::value();
  }
  static const char* value(const ::physarum_simulation::LockTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::physarum_simulation::LockTaskRequest> should match
// service_traits::DataType< ::physarum_simulation::LockTask >
template<>
struct DataType< ::physarum_simulation::LockTaskRequest>
{
  static const char* value()
  {
    return DataType< ::physarum_simulation::LockTask >::value();
  }
  static const char* value(const ::physarum_simulation::LockTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::physarum_simulation::LockTaskResponse> should match
// service_traits::MD5Sum< ::physarum_simulation::LockTask >
template<>
struct MD5Sum< ::physarum_simulation::LockTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::physarum_simulation::LockTask >::value();
  }
  static const char* value(const ::physarum_simulation::LockTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::physarum_simulation::LockTaskResponse> should match
// service_traits::DataType< ::physarum_simulation::LockTask >
template<>
struct DataType< ::physarum_simulation::LockTaskResponse>
{
  static const char* value()
  {
    return DataType< ::physarum_simulation::LockTask >::value();
  }
  static const char* value(const ::physarum_simulation::LockTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHYSARUM_SIMULATION_MESSAGE_LOCKTASK_H
