// Generated by gencpp from file physarum_simulation/LockTaskRequest.msg
// DO NOT EDIT!


#ifndef PHYSARUM_SIMULATION_MESSAGE_LOCKTASKREQUEST_H
#define PHYSARUM_SIMULATION_MESSAGE_LOCKTASKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace physarum_simulation
{
template <class ContainerAllocator>
struct LockTaskRequest_
{
  typedef LockTaskRequest_<ContainerAllocator> Type;

  LockTaskRequest_()
    : task_id()
    , robot_id()  {
    }
  LockTaskRequest_(const ContainerAllocator& _alloc)
    : task_id(_alloc)
    , robot_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_id_type;
  _task_id_type task_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_id_type;
  _robot_id_type robot_id;





  typedef boost::shared_ptr< ::physarum_simulation::LockTaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::physarum_simulation::LockTaskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LockTaskRequest_

typedef ::physarum_simulation::LockTaskRequest_<std::allocator<void> > LockTaskRequest;

typedef boost::shared_ptr< ::physarum_simulation::LockTaskRequest > LockTaskRequestPtr;
typedef boost::shared_ptr< ::physarum_simulation::LockTaskRequest const> LockTaskRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::physarum_simulation::LockTaskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::physarum_simulation::LockTaskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::physarum_simulation::LockTaskRequest_<ContainerAllocator1> & lhs, const ::physarum_simulation::LockTaskRequest_<ContainerAllocator2> & rhs)
{
  return lhs.task_id == rhs.task_id &&
    lhs.robot_id == rhs.robot_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::physarum_simulation::LockTaskRequest_<ContainerAllocator1> & lhs, const ::physarum_simulation::LockTaskRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace physarum_simulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::physarum_simulation::LockTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::physarum_simulation::LockTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::physarum_simulation::LockTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::physarum_simulation::LockTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::physarum_simulation::LockTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::physarum_simulation::LockTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::physarum_simulation::LockTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f35e3110319173bbacf96548119cb50";
  }

  static const char* value(const ::physarum_simulation::LockTaskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f35e3110319173bULL;
  static const uint64_t static_value2 = 0xbacf96548119cb50ULL;
};

template<class ContainerAllocator>
struct DataType< ::physarum_simulation::LockTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "physarum_simulation/LockTaskRequest";
  }

  static const char* value(const ::physarum_simulation::LockTaskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::physarum_simulation::LockTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string task_id\n"
"string robot_id\n"
;
  }

  static const char* value(const ::physarum_simulation::LockTaskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::physarum_simulation::LockTaskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_id);
      stream.next(m.robot_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LockTaskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::physarum_simulation::LockTaskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::physarum_simulation::LockTaskRequest_<ContainerAllocator>& v)
  {
    s << indent << "task_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_id);
    s << indent << "robot_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHYSARUM_SIMULATION_MESSAGE_LOCKTASKREQUEST_H
